In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = pd.DataFrame({"name" : ["a", "b", "c", "d"]})
df

  name
0    a
1    b
2    c
3    d

In [2]:
le.fit(df)

C:\Users\agraw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [3]:
le.transform(df)

C:\Users\agraw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0, 1, 2, 3])

In [4]:
df["e_name"] = le.fit_transform(df)

C:\Users\agraw\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [5]:
df.drop(columns = "name", inplace = True)

In [6]:
df

   e_name
0       0
1       1
2       2
3       3

In [8]:
ds = pd.read_csv("loan.csv.csv")
ds.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [11]:
ds["Property_Area"].unique()

<StringArray>
['Urban', 'Rural', 'Semiurban']
Length: 3, dtype: str

In [12]:
ds["Property_Area"] = le.fit_transform(ds["Property_Area"])

In [13]:
ds.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,2,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,2,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,1,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,2,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,1,N

In [15]:
ds["Education"] = ds["Education"].map({"Not Graduate" : 0, "Graduate" : 1, "NaN" : 2})

In [16]:
ds["Property_Area"].unique()

array([2, 0, 1])

In [17]:
ds.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,1,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,1,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,1,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,0,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,1,No,6000,0.0,141.0,360.0,1.0,2,Y

In [18]:
ds = pd.DataFrame({"size" : ["s","m","l","m","xl","s","l","xl"]})
ds

  size
0    s
1    m
2    l
3    m
4   xl
5    s
6    l
7   xl

In [19]:
data = [["s","m","l","xl"]]
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = data)

In [20]:
 oe.fit_transform(ds[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [3.],
       [0.],
       [2.],
       [3.]])

In [21]:
ds["size"] =  oe.fit_transform(ds[["size"]])
ds

   size
0   0.0
1   1.0
2   2.0
3   1.0
4   3.0
5   0.0
6   2.0
7   3.0

In [22]:
data1 = {"s" : 0, "m" : 1, "l" : 2, "xl" : 3}
df = pd.DataFrame({"size" : ["xl", "m", "s", "l", "s", "xl"]})
df["size"].map(data1)

0    3
1    1
2    0
3    2
4    0
5    3
Name: size, dtype: int64