In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Fishers maket.csv")

In [3]:
df.head(5)

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    str
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), str(1)
memory usage: 9.6 KB

In [5]:
df.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [6]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.shape

(159, 7)

In [11]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='str')

In [13]:
df["Species"].value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [14]:
df["Species"].nunique()

7

# check problem type

In [15]:
if df["Species"].nunique()>1:
    print("this problem is of classification")
else:
    print("regression problem")

this problem is of classification

# check dataset size

In [16]:
rows,cols=df.shape

In [17]:
rows

159

In [18]:
cols

7

In [20]:
if rows>100:
    print("bigger data")
else:
    print("very small data")

bigger data

# check data quality

In [21]:
if df.isnull().sum().sum()==0:
    print("good quality dataset")
else:
    print("bad quality")

good quality dataset

# algorithms

In [22]:
print("algorithms used")
print("1. Logistic Regression")
print("2. Decision Tree")
print("3. KNN")
print("4. Random Forest")
print("5. Naive Bayes")

algorithms used
1. Logistic Regression
2. Decision Tree
3. KNN
4. Random Forest
5. Naive Bayes